GO_EASY_ON_ME = 1

include theos/makefiles/common.mk

APPLICATION_NAME = iWebSearchPro
iWebSearchPro_FILES = main.m iWebSearchProApplication.mm RootViewController.mm SFAntiPiracy.m
iWebSearchPro_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
